# -*- coding: utf-8 -*-
"""EDA_week04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0-dJYZjC14-X1hMF-atnHr_KfQK6Yuf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv('/content/menu.csv')
#displaying the first few rows to understand the data
df.head()

#checking statistical facts
df.describe()

#calculating maximum values
max_values = df[['Calories', 'Total Fat', 'Carbohydrates', 'Dietary Fiber', 'Sugars',
                 'Protein', 'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
                 'Calcium (% Daily Value)', 'Iron (% Daily Value)']].max()
print("Maximum Values:")
print(max_values)

#plotting the correlation matrix
correlation = df[['Calories', 'Total Fat', 'Carbohydrates', 'Dietary Fiber', 'Sugars',
                  'Protein', 'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
                  'Calcium (% Daily Value)', 'Iron (% Daily Value)']].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Matrix')
plt.show()

plt.figure(figsize=(12, 8))
sns.boxplot(x='Calories', y='Category', data=df)
plt.xticks(rotation=90)
plt.title('Calories vs Category')

# Get unique categories for legend
categories = df['Category'].unique()

# Create legend labels
legend_labels = {category: category for category in categories}
handles = [plt.Rectangle((0,0),1,1, color=sns.color_palette()[i], label=label) for i, label in enumerate(legend_labels.values())]

# Plot legend at bottom right
plt.legend(handles=handles, title='Legend', loc='lower right')
plt.show()

# Function to get item with max value for each attribute
def get_max_item(attribute):
    max_item = df[df[attribute] == df[attribute].max()][['Item', attribute]]
    return max_item

# Getting items with max values for each attribute
attributes = ['Calories', 'Total Fat', 'Carbohydrates', 'Dietary Fiber', 'Sugars',
              'Protein', 'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
              'Calcium (% Daily Value)', 'Iron (% Daily Value)']

for attribute in attributes:
    max_item = get_max_item(attribute)
    print(f"Max {attribute}:")
    print(max_item)
    print()

#defining color palette
palette = sns.color_palette("tab10")

#loop through each attribute and create a strip plot
for attribute in attributes:
    plt.figure(figsize=(10, 6))
    sns.stripplot(x='Category', y=attribute, data=df, jitter=True, palette=palette)
    plt.title(f'{attribute} by Category')
    plt.xticks(rotation=90)
    plt.show()

#filter the data for each category
categories = df['Category'].unique()

for category in categories:
    plt.figure(figsize=(10, 6))
    category_data = df[df['Category'] == category]
    sns.barplot(x='Calories', y='Item', data=category_data, palette='Blues_r')
    plt.xlabel('Calories')
    plt.ylabel('Item')
    plt.title(f'Calories in {category}')
    plt.tight_layout()
    plt.show()

"""Observation:
**Breakfast:** Items in the Breakfast category generally have a wide range of calorie counts. Some items, like the Big Breakfast with Hotcakes, have high calories, while others like the Egg McMuffin are on the lower end.

**Beef & Pork:** This category tends to have higher calorie items, such as the Double Quarter Pounder with Cheese and the Bacon Clubhouse Burger.

**Chicken & Fish:** The calories in this category vary, with items like the Premium Grilled Chicken Classic Sandwich having lower calories compared to the Filet-O-Fish.

**Salads:** Salads are generally lower in calories, with the side Caesar Salad being one of the lowest.

**Snacks & Sides:** Items in this category, like the Apple Slices and the Kids French Fries, have relatively lower calories.

**Desserts:** Desserts like the McFlurry with M&M's Chocolate Candies and the Hot Caramel Sundae are higher in calories.

**Beverages:** Calorie counts in beverages vary widely, from the Fruit Punch to the large Coca-Cola.

**Smoothies & Shakes:** Items in this category, particularly the McCafe Strawberry Shake and the McCafe Chocolate Shake, have higher calories due to their creamy nature.

**Coffee & Tea:** This category generally has lower calorie items, such as the Premium Roast Coffee and the Iced Coffee.
"""